import Head from "next/head";
import React, { useRef } from "react";
import Avatar from "../Components/Avatar";
import { SearchIcon, ViewGridIcon } from "@heroicons/react/solid";
import { MicrophoneIcon } from "@heroicons/react/solid";
import Footer from "../Components/Footer";
import { useRouter } from "next/router";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  const router = useRouter();
  const searchInput = useRef(null);
  const search = event =>{
    event.preventDefault();
    const term = searchInput.current.value;
    if(!term) return;
router.push(`/search?term=${term}`)
  };
  return (
    <>
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>

        {/* Header */}
       <div className=" flex flex-col border-4 h-screen justify-center items-center"> 
        <header className="flex w-full p-5 justify-between text-gray-700 text-sm ">
          <div className="flex space-x-4 items-center">
            <p className="link">About</p>
            <p className="link">Store</p>
          </div>
          <div className="flex space-x-4 items-center">
          <Link href="https://mail.google.com/"><p className="link">Gmail</p></Link>
            <p className="link">Images</p>
            <ViewGridIcon className="h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer" />
            <Avatar />
          </div>
        </header>

        {/* body */}

        <form className="flex flex-col mt-44 items-center  flex-grow w-4/5">
          <Image src="https://www.google.co.in/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"
          alt="image"
          width="300"
          height="100"
            />
          <div className="flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg max-w-md rounded-full border-gray-200 border-2 px-1 py-3 items-center sm:max-w-xl lg:max-w-2xl">
            <SearchIcon className="h-5 mr-3 text-gray-500" />
            <input type="text" className=" focus:outline-none flex-grow " ref={searchInput}/>
            <MicrophoneIcon className="h-5 text-gray-500" />
          </div>
          <div className="flex flex-col space-y-2 w-1/2 justify-center mt-8
          sm:space-y-0 sm:space-x-4 sm:flex-row
          ">
            <button onClick={search} className="btn">Google Search</button>
            <button onClick={search} className="btn">I&apos;m Feeling Lucky</button>
          </div>
        </form>
     
        {/* footer */}
        <Footer/>
        </div>
     
    </>
  );
}
